name: Build Android App

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: 2. Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: 3. Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Set Play Store Name without forward slash
      - name: 4. Set playstore name as env variable
        run: echo "playstore_name=$(echo '${{ github.repository }}' | sed 's/\//-/')" >> $GITHUB_ENV

      - name: 5. Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: 6. Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: 7. Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: 8. Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: 9. Build apk debug project (APK)
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: 10. Build apk release project (APK)
        run: ./gradlew assemble

      # Create Bundle AAB Release
      - name: 11. Build app bundle release (AAB)
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload APK Debug
      - name: 12. Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-debug-apk
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Upload APK Release
      - name: 13. Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-release-apk
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Upload AAB Release
      - name: 14. Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-release-aab
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/